import type { Lang } from "@/components/landing-copy";

/**
 * Every visible string inside the product.
 *
 * Russian is the source table and English is checked against it, so a key
 * added on one side and forgotten on the other is a build error rather than a
 * blank label in production. Keys are flat with dotted prefixes on purpose:
 * a flat object gives `keyof typeof ru` a literal union, which is what makes
 * `<T k="dash.title" />` type-checked. Nesting would need a path lookup and
 * lose that.
 *
 * Names that are the same word in both languages (Telegram, Stripe, n8n,
 * JSON, API) are deliberately not translated.
 */
const ru = {
  // ——— Shell ———
  "nav.overview": "Обзор",
  "nav.outcomes": "Агенты",
  "nav.executions": "Разговоры",
  "nav.connections": "Каналы",
  "nav.templates": "Шаблоны",
  "nav.import": "Импорт из n8n",
  "nav.team": "Команда",
  "nav.usage": "Расход",
  "nav.billing": "Тариф",
  "nav.settings": "Настройки",
  "shell.search": "Поиск по агентам, запускам и справке",
  "shell.create": "Создать агента",
  "shell.workspace": "Рабочее пространство",
  "shell.manage": "Управление",
  "shell.signedIn": "Вы вошли",
  "shell.plan": "Тариф",
  "shell.upgradeFree": "Пробный период. Выберите тариф, чтобы агент работал дальше.",
  "shell.upgradePaid": "Посмотрите остаток лимитов, счета и настройки тарифа.",
  "shell.viewPlans": "Посмотреть тарифы",
  "shell.managePlan": "Управлять тарифом",
  "shell.closeNav": "Закрыть меню",
  "shell.openNav": "Открыть меню",
  "shell.account": "Меню аккаунта",
  "shell.demoUser": "Демо-пользователь",

  // ——— Общие ———
  "common.cancel": "Отмена",
  "common.save": "Сохранить",
  "common.saving": "Сохраняем…",
  "common.saved": "Сохранено",
  "common.dismiss": "Закрыть",
  "common.copy": "Копировать",
  "common.copied": "Скопировано",
  "common.manage": "Управлять",
  "common.viewAll": "Показать все",
  "common.edit": "Изменить",
  "common.required": "Обязательно",
  "common.noData": "Данные не записаны",
  "common.allStatuses": "Все статусы",
  "common.somethingWrong": "Что-то пошло не так",
  "common.theme": "Сменить тему",
  "common.home": "Rezaru — на главную",

  // ——— Статусы ———
  "status.SUCCEEDED": "успешно",
  "status.FAILED": "ошибка",
  "status.RUNNING": "выполняется",
  "status.QUEUED": "в очереди",
  "status.WAITING": "ожидание",
  "status.WAITING_FOR_APPROVAL": "ждёт подтверждения",
  "status.CANCELLED": "отменён",
  "status.TIMED_OUT": "истекло время",
  "status.ACTIVE": "активен",
  "status.PAUSED": "на паузе",
  "status.DRAFT": "черновик",
  "status.NEEDS_ATTENTION": "нужно внимание",
  "status.CONNECTED": "подключено",
  "status.PENDING": "в ожидании",

  // ——— Роли (приходят из базы, поэтому в том же словаре) ———
  "role.OWNER": "владелец",
  "role.ADMIN": "администратор",
  "role.BUILDER": "сборщик",
  "role.OPERATOR": "оператор",
  "role.VIEWER": "наблюдатель",

  // ——— Вход и регистрация ———
  "auth.titleRegister": "Создайте рабочее пространство",
  "auth.titleLogin": "С возвращением",
  "auth.titleForgot": "Сброс пароля",
  "auth.subRegister": "14 дней бесплатно. Карта не нужна.",
  "auth.subLogin": "Продолжайте работу со своими агентами.",
  "auth.subForgot": "Если аккаунт существует, мы пришлём безопасную ссылку для сброса.",
  "auth.name": "Имя и фамилия",
  "auth.namePlaceholder": "Алишер Рахимов",
  "auth.workspace": "Название пространства",
  "auth.workspacePlaceholder": "Кафе «Сомон»",
  "auth.email": "Электронная почта",
  "auth.emailPlaceholder": "vy@company.com",
  "auth.password": "Пароль",
  "auth.passwordPlaceholder": "Не меньше 8 символов",
  "auth.forgot": "Забыли пароль?",
  "auth.submitRegister": "Создать пространство",
  "auth.submitLogin": "Войти",
  "auth.submitForgot": "Отправить ссылку",
  "auth.or": "или войдите через",
  "auth.emailLink": "Ссылка на почту",
  "auth.haveAccount": "Уже есть аккаунт?",
  "auth.signIn": "Войти",
  "auth.newHere": "Впервые в Rezaru?",
  "auth.startFree": "Начать бесплатно",
  "auth.backToLogin": "Вернуться ко входу",
  "auth.quote": "«Настройки — это детали. Результат — вот продукт.»",
  "auth.step1": "Опишите, что должно происходить",
  "auth.step2": "Проверьте готовый план",
  "auth.step3": "Включите и следите за работой",
  "auth.resetSent": "Если аккаунт существует, ссылка для сброса уже в пути.",
  "auth.enterEmailFirst": "Сначала введите адрес почты.",
  "auth.linkFailed": "Не удалось отправить ссылку для входа",
  "auth.linkSent": "Безопасная ссылка для входа отправлена.",
  "auth.workspaceFailed": "Не удалось создать рабочее пространство",
  "auth.checkInbox": "Проверьте почту",
  "auth.checkInboxCopy": "Откройте ссылку из письма, чтобы завершить настройку аккаунта Rezaru.",
  "auth.inviteJoin": "Присоединиться к",
  "auth.inviteBad": "Приглашение недоступно",
  "auth.inviteBadCopy": "Это приглашение недействительно, истекло или уже использовано.",
  "auth.inviteAccept": "Принять приглашение",
  "auth.inviteHome": "На главную",
  "auth.inviteRole": "Вас пригласили с ролью",
  "auth.inviteTail": "Войдите или создайте аккаунт, чтобы продолжить.",

  // ——— Первый запуск ———
  "onb.setup": "Настройка пространства",
  "onb.welcome": "ДОБРО ПОЖАЛОВАТЬ",
  "onb.title1": "Пусть Rezaru принесёт пользу",
  "onb.title2": "с первого же запуска.",
  "onb.lead": "Расскажите немного о работе. Мы предложим готовые сценарии, а не пустые настройки.",
  // The three questions themselves live in landing-copy, so the site and the
  // first screen cannot drift apart. Only the frame around them is here.
  "onb.build": "Собрать этого агента",
  "onb.skip": "Показать панель",

  // ——— Панель ———
  "dash.eyebrow": "ОБЗОР РАБОТЫ",
  "dash.morning": "Доброе утро.",
  "dash.afternoon": "Добрый день.",
  "dash.evening": "Добрый вечер.",
  "dash.leadTail": "работает штатно. Вот что сделал Rezaru.",
  "dash.create": "Создать агента",
  "dash.mActive": "Активных агентов",
  "dash.mActiveDetail": "всего",
  "dash.mToday": "Запусков сегодня",
  "dash.mTodayDetail": "успешных",
  "dash.mRate": "Доля успешных",
  "dash.mRateDetail": "по сегодняшним запускам",
  "dash.mRateNone": "Сбоев сегодня нет",
  "dash.mSaved": "Сэкономлено времени",
  "dash.mSavedDetail": "за этот месяц",
  "dash.recent": "Последние запуски",
  "dash.recentSub": "Живая активность по активным агентам.",
  "dash.noRuns": "Запусков пока нет",
  "dash.noRunsSub": "Проверьте агента на тесте или включите его — активность появится здесь.",
  "dash.buildFirst": "Собрать агента",
  "dash.attention": "Нужно внимание",
  "dash.attentionSub": "Ждут вашего решения.",
  "dash.reviewFails": "Разобрать недавние сбои",
  "dash.healthy": "Всё в порядке",
  "dash.healthySub": "Сейчас ни один агент не требует внимания.",
  "dash.activeOutcomes": "Активные агенты",
  "dash.activeOutcomesSub": "Работают вместо вас каждый день.",
  "dash.firstOutcome": "Первый агент начинается с одной фразы",
  "dash.firstOutcomeSub": "Опишите повторяющуюся работу и проверьте готовый план.",
  "dash.improvements": "Улучшения от ИИ",
  "dash.improvementsSub": "Предложения на ваше подтверждение, основанные на фактах.",
  "dash.learning": "Учимся на истории запусков",
  "dash.learningSub": "Предложения появятся, когда наберётся достаточно данных.",
  "dash.simulated": "Тестовый · ",
  "dash.hours": "ч",

  // ——— Агенты ———
  "out.eyebrow": "АВТОМАТИЗАЦИЯ",
  "out.title": "Агенты",
  "out.lead": "Результаты, которые Rezaru создаёт, выполняет и улучшает.",
  "out.search": "Поиск по агентам…",
  "out.fActive": "Активные",
  "out.fDraft": "Черновики",
  "out.fAttention": "Нужно внимание",
  "out.filter": "Фильтр агентов",
  "out.runs": "запусков",
  "out.version": "версия",
  "out.emptyTitle": "Создайте первого агента",
  "out.emptyCopy": "Опишите повторяющуюся работу. Rezaru спросит только необходимое и покажет план, который можно проверить.",
  "out.fromTemplate": "Взять готовый шаблон",
  "out.detailVersion": "Версия",
  "out.tabOverview": "Обзор",
  "out.tabExecutions": "Запуски",
  "out.tabEdit": "Изменить",
  "out.plan": "План агента",
  "out.planSub": "Понятное описание работы, которое сейчас на проверке.",
  "out.editWithAi": "Изменить через ИИ",
  "out.technical": "Техническая схема",
  "out.technicalSub": "Реализация только для просмотра — собрана из плана.",
  "out.advanced": "Подробный вид",
  "out.requiredConn": "Нужные подключения",
  "out.noConn": "Этот агент использует только встроенные операции.",
  "out.recent": "Последние запуски",
  "out.noRuns": "Запусков пока нет. Сделайте тестовый прогон перед включением.",
  "out.improvements": "Улучшения",
  "out.duplicate": "Дублировать",
  "out.test": "Тест",
  "out.pause": "Пауза",
  "out.activate": "Включить",
  "out.actionFailed": "Действие не выполнено",

  // ——— Конструктор ———
  "comp.eyebrow": "СБОРКА АГЕНТА",
  "comp.title": "Соберите агента",
  "comp.draft": "Черновик сохранён локально",
  "comp.save": "Сохранить агента",
  "comp.architect": "Помощник по сборке",
  "comp.architectSub": "Собирает только из проверенных операций",
  "comp.online": "НА СВЯЗИ",
  "comp.you": "Вы",
  "comp.greeting": "Опишите, какой результат вам нужен. Я определю событие-триггер, действия и нужные подключения, а спрошу только то, без чего план не собрать.",
  "comp.requiredDetail": "НУЖНА ДЕТАЛЬ",
  "comp.answerPlaceholder": "Куда отправлять результат…",
  "comp.buildPlan": "Собрать рабочий план",
  "comp.validating": "Проверяем смысл, безопасность и стоимость…",
  "comp.tryExample": "ПОПРОБУЙТЕ ПРИМЕР",
  "comp.modifyPlaceholder": "Добавить подтверждение, поменять сервис, сделать дешевле…",
  "comp.describePlaceholder": "Опишите, что должен делать агент…",
  "comp.hint": "Например: «Повторяй при сбое три раза»",
  "comp.send": "Отправить сообщение",
  "comp.tabPlan": "План",
  "comp.tabTechnical": "Схема",
  "comp.tabTest": "Тестовые данные",
  "comp.tabSettings": "Настройки",
  "comp.tabVersions": "Версии",
  "comp.emptyTitle": "Здесь появится план",
  "comp.emptyCopy": "Rezaru превратит вашу задачу в понятный план, список нужных подключений и проверенную техническую схему.",
  "comp.pendingTitle": "Схема пока не готова",
  "comp.pendingCopy": "Ответьте на обязательные вопросы — после этого Rezaru соберёт исполняемую схему.",
  "comp.sampleTitle": "Пример входных данных",
  "comp.sampleCopy": "Эти данные изолированы от рабочих и помечаются как тест.",
  "comp.validateSample": "Проверить пример",
  "comp.execSettings": "Настройки выполнения",
  "comp.concurrency": "Одновременных запусков",
  "comp.concurrencyUnit": "запусков",
  "comp.timeout": "Ограничение по времени",
  "comp.timezone": "Часовой пояс",
  "comp.retention": "Хранение истории",
  "comp.days": "дней",
  "comp.currentDraft": "Текущий черновик",
  "comp.createdBy": "Создан конструктором Rezaru",
  "comp.draftBadge": "Черновик",
  "comp.versionNote": "После включения версия становится неизменной. Следующие правки создают новый черновик.",
  "comp.perMonth": "запусков в месяц",
  "comp.saveReview": "Сохранить и проверить",
  "comp.outcome": "РЕЗУЛЬТАТ",
  "comp.validated": "Проверен",
  "comp.needsInput": "Нужны данные",
  "comp.connNeeded": "нужных подключений",
  "comp.connNeededSub": "Подключите их на этапе проверки. Пароли и ключи в план не попадают.",
  "comp.assumptions": "ДОПУЩЕНИЯ",
  "comp.compileFailed": "Не удалось собрать агента",
  "comp.saveFailed": "Не удалось сохранить агента",
  "comp.needDetailOne": "Я понял задачу. Нужна ещё одна деталь, чтобы собрать безопасную рабочую версию.",
  "comp.needDetailMany": "Я понял задачу. Нужно ещё несколько деталей, чтобы собрать безопасную рабочую версию.",
  "comp.planReady": "План готов.",
  "comp.planSteps": "шагов",
  "comp.planConn": "нужных подключений",
  "comp.planRuns": "запусков в месяц (примерно)",
  "comp.starter1": "Отвечать в Instagram на вопросы о цене и наличии.",
  "comp.starter2": "Каждый понедельник присылать сводку продаж за неделю.",
  "comp.starter3": "Записывать заказы из Telegram в таблицу.",
  "comp.starter4": "Напоминать клиенту о записи за день до визита.",

  // ——— Запуски ———
  "exec.eyebrow": "НАДЁЖНОЕ ВЫПОЛНЕНИЕ",
  "exec.title": "История запусков",
  "exec.lead": "Смотрите каждый запуск: шаги, повторы, ожидания, стоимость и результат.",
  "exec.search": "Поиск по запускам…",
  "exec.filterStatus": "Фильтр по статусу",
  "exec.fSucceeded": "Успешные",
  "exec.fFailed": "С ошибкой",
  "exec.fRunning": "Выполняются",
  "exec.filters": "Фильтры",
  "exec.colOutcome": "Агент",
  "exec.colStatus": "Статус",
  "exec.colStarted": "Начало",
  "exec.colDuration": "Длительность",
  "exec.colSteps": "Шаги",
  "exec.simulated": "Тестовый запуск",
  "exec.emptyTitle": "Запусков пока нет",
  "exec.emptyCopy": "Проверьте агента на тестовых данных или включите его — история появится здесь.",
  "exec.back": "История запусков",
  "exec.workflowVersion": "Схема v",
  "exec.execution": "Запуск",
  "exec.duration": "Длительность",
  "exec.inProgress": "Идёт",
  "exec.cost": "Примерная стоимость",
  "exec.tokens": "Токены ИИ",
  "exec.started": "Начало",
  "exec.triggerInput": "Входные данные",
  "exec.triggerInputSub": "Пароли и поля, помеченные как скрытые, замаскированы.",
  "exec.metadata": "Данные о запуске",
  "exec.metaOutcome": "Агент",
  "exec.metaVersion": "Версия",
  "exec.metaMode": "Режим",
  "exec.metaSteps": "Шагов",
  "exec.live": "Обновления в реальном времени",
  "exec.timeline": "Ход выполнения",
  "exec.cancel": "Остановить",
  "exec.retry": "Повторить шаг с ошибкой",
  "exec.step": "ШАГ",
  "exec.attempt": "попытка",
  "exec.attempts": "попыток",
  "exec.ms": "мс",
  "exec.input": "Вход",
  "exec.output": "Результат",
  "exec.error": "Ошибка",
  "exec.logs": "Журнал",
  "exec.debugTitle": "Разбор от ИИ",
  "exec.debugSub": "Опирается только на записи этого запуска",
  "exec.whyFailed": "Почему не получилось?",
  "exec.plainLanguage": "Объяснить простыми словами",
  "exec.proposeFix": "Предложить решение",
  "exec.addFallback": "Предложить запасной вариант",
  "exec.reviewing": "Читаем записи запуска…",
  "exec.noExplanation": "Достоверного объяснения нет.",

  // ——— Схема ———
  "flow.aria": "Схема работы агента, только для просмотра",
  "flow.yes": "да",
  "flow.no": "нет",
  "flow.trigger": "событие",
  "flow.action": "действие",
  "flow.condition": "условие",
  "flow.transform": "преобразование",
  "flow.delay": "пауза",
  "flow.approval": "подтверждение",
  "flow.ai_task": "задача ИИ",
  "flow.startNode": "Начало",

  // ——— Подключения ———
  "conn.eyebrow": "БЕЗОПАСНЫЕ ИНТЕГРАЦИИ",
  "conn.title": "Подключения",
  "conn.lead": "Подключите сервисы, которыми Rezaru будет пользоваться от вашего имени. Ключи хранятся зашифрованными на сервере.",
  "conn.yours": "Ваши подключения",
  "conn.configured": "настроено",
  "conn.usedBy": "используют агентов:",
  "conn.test": "Проверить",
  "conn.delete": "Удалить",
  "conn.market": "Каталог сервисов",
  "conn.approved": "проверенных сервисов",
  "conn.search": "Поиск по сервисам…",
  "conn.all": "Все",
  "conn.connected": "Подключено",
  "conn.noCreds": "Без ключей",
  "conn.addAnother": "Добавить ещё",
  "conn.connect": "Подключить",
  "conn.dialogTitle": "Подключение:",
  "conn.oauthSetup": "Настройка OAuth",
  "conn.oauthCopy": "Для OAuth на сервере задайте переменные:",
  "conn.oauthTail": "Для локальной разработки можно ввести готовый токен ниже.",
  "conn.name": "Название подключения",
  "conn.connectionString": "Строка подключения",
  "conn.apiKey": "Ключ API",
  "conn.accessToken": "Токен доступа OAuth",
  "conn.credPlaceholderDev": "Введите «demo» для тестового подключения",
  "conn.credPlaceholder": "Хранится в зашифрованном виде",
  "conn.connectAndTest": "Подключить и проверить",
  "conn.failed": "Не удалось подключить",
  "conn.testFailed": "Проверка не прошла",
  "conn.confirmDelete": "Удалить подключение? Зашифрованные ключи будут удалены вместе с ним.",
  "conn.suffix": " — подключение",
  "conn.docs": "Где взять эти данные — пошаговая инструкция",
  "conn.channels": "Каналы",
  "conn.catCommunication": "Почта и чаты",
  "conn.catCRM": "CRM",
  "conn.catMarketing": "Маркетинг",
  "conn.catFinance": "Финансы",
  "conn.catDatabases": "Базы данных",
  "conn.catAI": "ИИ",
  "conn.catDeveloper": "Для разработчиков",
  "conn.catProductivity": "Работа с данными",

  // ——— Шаблоны ———
  "tpl.eyebrow": "КАТАЛОГ ГОТОВЫХ АГЕНТОВ",
  "tpl.title": "Шаблоны",
  "tpl.lead": "Возьмите готовый сценарий и настройте только то, что относится именно к вам.",
  "tpl.search": "Поиск по шаблонам…",
  "tpl.all": "Все",
  "tpl.setup": "мин на настройку",
  "tpl.saves": "Экономит",
  "tpl.savesUnit": "ч/мес",
  "tpl.preview": "Посмотреть шаблон",
  "tpl.minutes": "минут на настройку",
  "tpl.savesAbout": "Экономит примерно",
  "tpl.hoursMonth": "часов в месяц",
  "tpl.requiredConn": "Нужные подключения",
  "tpl.install": "Установить как черновик",
  "tpl.installFailed": "Не удалось установить",

  // ——— Импорт ———
  "imp.eyebrow": "БЕЗОПАСНЫЙ ПЕРЕЕЗД",
  "imp.title": "Импорт из n8n",
  "imp.lead": "Проверим совместимость, сопоставим ключи и дадим протестировать результат до включения.",
  "imp.upload": "Загрузить JSON",
  "imp.orPaste": "или вставьте выгрузку ниже",
  "imp.analyze": "Проверить совместимость",
  "imp.next": "Что будет дальше",
  "imp.next1": "Мы находим все узлы из выгрузки",
  "imp.next2": "Поддерживаемые узлы становятся проверенными операциями",
  "imp.next3": "Частично поддерживаемые помечаются для проверки",
  "imp.next4": "Неподдерживаемый код превращается в безопасную заглушку",
  "imp.next5": "Исходный JSON сохраняется",
  "imp.next6": "Ничего не запустится, пока вы не протестируете и не включите",
  "imp.report": "ОТЧЁТ О СОВМЕСТИМОСТИ N8N",
  "imp.nodesAnalyzed": "узлов проверено",
  "imp.convertible": "переносится",
  "imp.supported": "Поддержано",
  "imp.partial": "Частично",
  "imp.manual": "Ручная проверка",
  "imp.colNode": "Узел",
  "imp.colType": "Тип в n8n",
  "imp.colOperation": "Операция Rezaru",
  "imp.colCompat": "Совместимость",
  "imp.placeholder": "Заглушка для ручной проверки",
  "imp.backToSource": "Назад к исходнику",
  "imp.convert": "Превратить в черновик агента",
  "imp.badJson": "Вставленный текст не является корректным JSON.",
  "imp.tooBig": "Выгрузка n8n должна быть меньше 5 МБ.",
  "imp.analysisFailed": "Не удалось проверить выгрузку",
  "imp.conversionFailed": "Не удалось преобразовать",

  // ——— Команда ———
  "team.eyebrow": "ЛЮДИ И ДОСТУПЫ",
  "team.title": "Команда",
  "team.lead": "Дайте сотрудникам ровно тот доступ, который им нужен.",
  "team.members": "Участники пространства",
  "team.membersCount": "человек имеют доступ.",
  "team.colMember": "Участник",
  "team.colRole": "Роль",
  "team.colAccess": "Доступ",
  "team.unnamed": "Без имени",
  "team.owner": "Владелец",
  "team.accessRead": "Только чтение",
  "team.accessRun": "Запуск и подтверждение",
  "team.accessBuild": "Сборка и управление",
  "team.invite": "Пригласить сотрудника",
  "team.inviteSub": "Ссылка-приглашение действует семь дней.",
  "team.inviteEmail": "Почта",
  "team.inviteEmailPlaceholder": "kollega@company.com",
  "team.inviteRole": "Роль",
  "team.inviteCreate": "Создать приглашение",
  "team.inviteFailed": "Не удалось отправить приглашение",
  "team.inviteCreated": "Приглашение создано. Письмо уйдёт через настроенный сервис почты.",
  "team.copyInvite": "Скопировать ссылку приглашения",
  "team.pending": "Ожидают приглашения",
  "team.expires": "Действует до",
  "team.roleGuide": "Что может каждая роль",
  "team.roleOwner": "Владелец",
  "team.roleOwnerCopy": "Всё, включая передачу прав и оплату",
  "team.roleAdmin": "Администратор",
  "team.roleAdminCopy": "Команда, оплата, подключения и агенты",
  "team.roleBuilder": "Сборщик",
  "team.roleBuilderCopy": "Создание, правка, тесты и подключения",
  "team.roleOperator": "Оператор",
  "team.roleOperatorCopy": "Запуск, пауза, повтор и подтверждения",
  "team.roleViewer": "Наблюдатель",
  "team.roleViewerCopy": "Просмотр агентов и истории запусков",

  // ——— Расход ———
  "usage.eyebrow": "ЛИМИТЫ И РАСХОД",
  "usage.title": "Расход",
  "usage.lead": "Понятный расход пространства за текущий период оплаты.",
  "usage.managePlan": "Управлять тарифом",
  "usage.currentPlan": "Текущий тариф",
  "usage.period": "Период оплаты",
  "usage.periodValue": "Текущий календарный месяц",
  "usage.behavior": "При достижении лимита",
  "usage.behaviorValue": "Лишние запуски встают на паузу",
  "usage.custom": "Без ограничений",
  "usage.used": "использовано",
  "usage.levelWarning": "Приближаетесь к лимиту тарифа",
  "usage.levelCritical": "Рекомендуем перейти на тариф выше",
  "usage.levelBlocked": "Лимит исчерпан",
  "usage.levelOk": "В пределах тарифа",
  "usage.mOutcomes": "Активных агентов",
  "usage.mExecutions": "Разговоров",
  "usage.mCredits": "Кредитов ИИ",
  "usage.mMembers": "Участников команды",
  "usage.noticeTitle": "Лимиты проверяются на сервере",
  "usage.noticeCopy": "Rezaru никогда не удаляет агентов при достижении лимита. Лишние запуски встают на паузу и появляется предложение расширить тариф.",

  // ——— Оплата ———
  "bill.eyebrow": "ТАРИФ И ОПЛАТА",
  "bill.title": "Оплата",
  "bill.lead": "Выберите объём работы, который нужен вашему бизнесу.",
  "bill.devTitle": "Режим разработки",
  "bill.devCopy": "Ключи Stripe не настроены. Смена тарифа меняет локальные лимиты и не списывает деньги.",
  "bill.current": "ТЕКУЩИЙ ТАРИФ",
  "bill.plan": "ТАРИФ",
  "bill.localSub": "Локальная подписка для разработки",
  "bill.stripeSub": "Управляется через Stripe",
  "bill.manageSub": "Управлять подпиской",
  "bill.monthly": "Помесячно",
  "bill.annual": "На год",
  "bill.save20": "Выгода 20%",
  "bill.perMonth": "/мес",
  "bill.currentPlan": "Текущий тариф",
  "bill.choose": "Выбрать",
  "bill.nameFree": "Пробный",
  "bill.namePro": "Старт",
  "bill.nameTeam": "Бизнес",
  "bill.nameBusiness": "Сеть",
  "bill.freeCopy": "14 дней, чтобы проверить на своей задаче",
  "bill.proCopy": "Когда пишут несколько раз в день",
  "bill.teamCopy": "Когда сообщений много каждый день",
  "bill.businessCopy": "Несколько точек или команд",
  "bill.proF1": "До 300 разговоров в месяц",
  "bill.proF2": "Один канал на выбор",
  "bill.proF3": "База знаний по вашему прайсу",
  "bill.proF4": "Запись в календарь",
  "bill.proF5": "Поддержка по почте",
  "bill.teamF1": "До 2 000 разговоров в месяц",
  "bill.teamF2": "Все каналы сразу",
  "bill.teamF3": "Напоминания и допродажи",
  "bill.teamF4": "Отчёты и сводки",
  "bill.teamF5": "Приоритетная поддержка",
  "bill.businessF1": "Несколько точек и команд",
  "bill.businessF2": "Свой стиль общения агента",
  "bill.businessF3": "Интеграции под вашу задачу",
  "bill.businessF4": "Персональный менеджер",
  "bill.businessTitle": "Несколько точек, свои интеграции и договор об уровне сервиса.",
  "bill.businessPrice": "Индивидуально",
  "bill.businessNote": "Зависит от числа точек и объёма разговоров",
  "bill.contact": "Обсудить",
  "bill.trialNote": "Первые 14 дней бесплатно. Карта не нужна, само ничего не спишется.",
  "bill.failed": "Не удалось выполнить действие с оплатой",
  "bill.updated": "Тариф обновлён",
  "bill.portalUnavailable": "Личный кабинет оплаты недоступен",

  // ——— Настройки ———
  "set.eyebrow": "НАСТРОЙКИ ПРОСТРАНСТВА",
  "set.title": "Настройки",
  "set.lead": "Название пространства и основные рабочие предпочтения.",
  "set.general": "Общие",
  "set.security": "Безопасность и журнал",
  "set.apiKeys": "Ключи API",
  "set.webhooks": "Вебхуки",
  "set.details": "Данные пространства",
  "set.detailsSub": "Используются в меню, приглашениях и счетах.",
  "set.name": "Название пространства",
  "set.slug": "Короткий адрес",
  "set.dept": "Направление",
  "set.size": "Размер компании",
  "set.saveSettings": "Сохранить настройки",
  "set.groupSpace": "Пространство",
  "set.groupDev": "Для разработчиков",
  "set.back": "Назад в настройки",

  // ——— Безопасность ———
  "sec.eyebrow": "БЕЗОПАСНОСТЬ И ДОВЕРИЕ",
  "sec.title": "Безопасность",
  "sec.lead": "Защита ключей, контроль доступа и журнал действий в пространстве.",
  "sec.encTitle": "Зашифрованные ключи",
  "sec.encCopy": "Шифрование AES-256-GCM с проверкой целостности и отдельным хранением секретов.",
  "sec.isoTitle": "Изоляция пространств",
  "sec.isoCopy": "Каждый запрос к данным ограничен вашим рабочим пространством.",
  "sec.keyTitle": "Ключи API в виде хэшей",
  "sec.keyCopy": "Полный ключ показывается один раз и не хранится в восстановимом виде.",
  "sec.audit": "Журнал действий",
  "sec.auditSub": "Действия, важные для безопасности.",
  "sec.system": "Система",

  // ——— Ключи API ———
  "key.eyebrow": "ДОСТУП ДЛЯ РАЗРАБОТЧИКОВ",
  "key.title": "Ключи API",
  "key.lead": "Запускайте агентов и смотрите результаты из своего приложения.",
  "key.copyNow": "Скопируйте ключ сейчас",
  "key.copyNowSub": "Он больше не будет показан.",
  "key.list": "Ключи пространства",
  "key.listSub": "Мы храним только префикс и хэш.",
  "key.used": "Использован",
  "key.neverUsed": "Не использовался",
  "key.none": "Ключи API ещё не создавались.",
  "key.create": "Создать ключ API",
  "key.createSub": "Давайте интеграции только те права, которые ей нужны.",
  "key.name": "Название ключа",
  "key.namePlaceholder": "Рабочий сервер",
  "key.scopes": "Права",
  "key.generate": "Создать ключ",
  "key.confirmRevoke": "Отозвать этот ключ? Интеграции, которые им пользуются, перестанут работать.",
  "key.quickstart": "Быстрый старт для разработчика",
  "key.quickstartSub": "Токен в заголовке Authorization, тело в JSON. На каждый ключ действуют ограничения по частоте.",
  "key.epList": "Список агентов",
  "key.epTrigger": "Запустить агента",
  "key.epExecutions": "Список запусков",
  "key.epExecution": "Подробности запуска",

  // ——— Вебхуки ———
  "hook.eyebrow": "ВХОДЯЩИЕ СОБЫТИЯ",
  "hook.title": "Вебхуки",
  "hook.lead": "Создавайте тестовые и рабочие адреса с проверкой по секретному ключу.",
  "hook.copyNow": "Скопируйте адрес сейчас",
  "hook.copyNowSub": "Полный токен больше не будет показан.",
  "hook.list": "Адреса вебхуков",
  "hook.listSub": "Тестовые адреса имитируют запуск; рабочие требуют включённого агента.",
  "hook.created": "Создан",
  "hook.sample": "Пример сохранён",
  "hook.none": "Адресов вебхуков пока нет.",
  "hook.create": "Создать адрес",
  "hook.createSub": "Адрес нельзя угадать, и показывается он один раз. При желании добавьте секретный заголовок.",
  "hook.outcome": "Агент",
  "hook.mode": "Режим",
  "hook.modeTest": "Тест — имитация",
  "hook.modeProd": "Рабочий — настоящий запуск",
  "hook.secret": "Секрет для проверки (необязательно)",
  "hook.secretPlaceholder": "Передаётся в заголовке x-rezaru-secret",
  "hook.createSecure": "Создать защищённый адрес"
};

export type UiCopyKey = keyof typeof ru;

const en: Record<UiCopyKey, string> = {
  // ——— Shell ———
  "nav.overview": "Overview",
  "nav.outcomes": "Agents",
  "nav.executions": "Conversations",
  "nav.connections": "Channels",
  "nav.templates": "Templates",
  "nav.import": "Import from n8n",
  "nav.team": "Team",
  "nav.usage": "Usage",
  "nav.billing": "Plan",
  "nav.settings": "Settings",
  "shell.search": "Search agents, executions and docs",
  "shell.create": "Create agent",
  "shell.workspace": "Workspace",
  "shell.manage": "Manage",
  "shell.signedIn": "Signed in",
  "shell.plan": "plan",
  "shell.upgradeFree": "Trial period. Choose a plan to keep the agent running.",
  "shell.upgradePaid": "Review capacity, invoices and plan controls.",
  "shell.viewPlans": "View plans",
  "shell.managePlan": "Manage plan",
  "shell.closeNav": "Close navigation",
  "shell.openNav": "Open navigation",
  "shell.account": "Account menu",
  "shell.demoUser": "Demo operator",

  // ——— Common ———
  "common.cancel": "Cancel",
  "common.save": "Save",
  "common.saving": "Saving…",
  "common.saved": "Saved",
  "common.dismiss": "Dismiss",
  "common.copy": "Copy",
  "common.copied": "Copied",
  "common.manage": "Manage",
  "common.viewAll": "View all",
  "common.edit": "Edit",
  "common.required": "Required",
  "common.noData": "No data recorded",
  "common.allStatuses": "All statuses",
  "common.somethingWrong": "Something went wrong",
  "common.theme": "Switch theme",
  "common.home": "Rezaru home",

  // ——— Statuses ———
  "status.SUCCEEDED": "succeeded",
  "status.FAILED": "failed",
  "status.RUNNING": "running",
  "status.QUEUED": "queued",
  "status.WAITING": "waiting",
  "status.WAITING_FOR_APPROVAL": "waiting for approval",
  "status.CANCELLED": "cancelled",
  "status.TIMED_OUT": "timed out",
  "status.ACTIVE": "active",
  "status.PAUSED": "paused",
  "status.DRAFT": "draft",
  "status.NEEDS_ATTENTION": "needs attention",
  "status.CONNECTED": "connected",
  "status.PENDING": "pending",

  // ——— Roles ———
  "role.OWNER": "owner",
  "role.ADMIN": "admin",
  "role.BUILDER": "builder",
  "role.OPERATOR": "operator",
  "role.VIEWER": "viewer",

  // ——— Auth ———
  "auth.titleRegister": "Create your workspace",
  "auth.titleLogin": "Welcome back",
  "auth.titleForgot": "Reset your password",
  "auth.subRegister": "14 days free. No card needed.",
  "auth.subLogin": "Continue running your agents.",
  "auth.subForgot": "We’ll send a secure reset link if your account exists.",
  "auth.name": "Full name",
  "auth.namePlaceholder": "Alisher Rahimov",
  "auth.workspace": "Workspace name",
  "auth.workspacePlaceholder": "Somon Café",
  "auth.email": "Email address",
  "auth.emailPlaceholder": "you@company.com",
  "auth.password": "Password",
  "auth.passwordPlaceholder": "At least 8 characters",
  "auth.forgot": "Forgot password?",
  "auth.submitRegister": "Create workspace",
  "auth.submitLogin": "Sign in",
  "auth.submitForgot": "Send reset link",
  "auth.or": "or continue with",
  "auth.emailLink": "Email link",
  "auth.haveAccount": "Already have an account?",
  "auth.signIn": "Sign in",
  "auth.newHere": "New to Rezaru?",
  "auth.startFree": "Start free",
  "auth.backToLogin": "Return to sign in",
  "auth.quote": "“The setup is an implementation detail. The outcome is the product.”",
  "auth.step1": "Describe what should happen",
  "auth.step2": "Review the generated plan",
  "auth.step3": "Activate and watch it run",
  "auth.resetSent": "If an account exists, a reset link is on its way.",
  "auth.enterEmailFirst": "Enter your email address first.",
  "auth.linkFailed": "Could not send the sign-in link",
  "auth.linkSent": "Your secure sign-in link has been sent.",
  "auth.workspaceFailed": "Could not create the workspace",
  "auth.checkInbox": "Check your inbox",
  "auth.checkInboxCopy": "Open the verification link we sent to finish securing your Rezaru account.",
  "auth.inviteJoin": "Join",
  "auth.inviteBad": "Invitation unavailable",
  "auth.inviteBadCopy": "This invitation is invalid, expired, or has already been used.",
  "auth.inviteAccept": "Accept invitation",
  "auth.inviteHome": "Return home",
  "auth.inviteRole": "You have been invited as",
  "auth.inviteTail": "Sign in or create an account to continue.",

  // ——— Onboarding ———
  "onb.setup": "Workspace setup",
  "onb.welcome": "WELCOME TO",
  "onb.title1": "Make Rezaru useful",
  "onb.title2": "from the first run.",
  "onb.lead": "Tell us a little about your work. We’ll suggest ready scenarios, not empty settings.",
  "onb.build": "Build this agent",
  "onb.skip": "Show my dashboard",

  // ——— Dashboard ———
  "dash.eyebrow": "OPERATIONS OVERVIEW",
  "dash.morning": "Good morning.",
  "dash.afternoon": "Good afternoon.",
  "dash.evening": "Good evening.",
  "dash.leadTail": "is operating normally. Here’s what Rezaru handled.",
  "dash.create": "Create agent",
  "dash.mActive": "Active agents",
  "dash.mActiveDetail": "total",
  "dash.mToday": "Executions today",
  "dash.mTodayDetail": "successful",
  "dash.mRate": "Success rate",
  "dash.mRateDetail": "across today’s runs",
  "dash.mRateNone": "No failures today",
  "dash.mSaved": "Estimated time saved",
  "dash.mSavedDetail": "this month",
  "dash.recent": "Recent executions",
  "dash.recentSub": "Live activity across active agents.",
  "dash.noRuns": "No executions yet",
  "dash.noRunsSub": "Test or activate an agent to see live activity here.",
  "dash.buildFirst": "Build an agent",
  "dash.attention": "Needs attention",
  "dash.attentionSub": "Items waiting for your decision.",
  "dash.reviewFails": "Review recent failures",
  "dash.healthy": "Everything looks healthy",
  "dash.healthySub": "No agent needs attention right now.",
  "dash.activeOutcomes": "Active agents",
  "dash.activeOutcomesSub": "Running on your behalf every day.",
  "dash.firstOutcome": "Your first agent starts with a sentence",
  "dash.firstOutcomeSub": "Describe repetitive work and review the generated plan.",
  "dash.improvements": "AI improvements",
  "dash.improvementsSub": "Evidence-backed suggestions for your approval.",
  "dash.learning": "Learning from execution history",
  "dash.learningSub": "Suggestions appear once there is enough evidence.",
  "dash.simulated": "Simulated · ",
  "dash.hours": "h",

  // ——— Agents ———
  "out.eyebrow": "AUTOMATED OPERATIONS",
  "out.title": "Agents",
  "out.lead": "Results that Rezaru creates, runs and improves.",
  "out.search": "Search agents…",
  "out.fActive": "Active",
  "out.fDraft": "Draft",
  "out.fAttention": "Needs attention",
  "out.filter": "Filter agents",
  "out.runs": "executions",
  "out.version": "version",
  "out.emptyTitle": "Define your first agent",
  "out.emptyCopy": "Describe repetitive work. Rezaru will ask only for what it needs and show a plan you can test.",
  "out.fromTemplate": "Start from a template",
  "out.detailVersion": "Version",
  "out.tabOverview": "Overview",
  "out.tabExecutions": "Executions",
  "out.tabEdit": "Edit",
  "out.plan": "Agent plan",
  "out.planSub": "The human-readable operation currently under review.",
  "out.editWithAi": "Edit with AI",
  "out.technical": "Technical flow",
  "out.technicalSub": "Read-only implementation generated from the plan.",
  "out.advanced": "Advanced view",
  "out.requiredConn": "Required connections",
  "out.noConn": "This agent uses built-in operations only.",
  "out.recent": "Recent executions",
  "out.noRuns": "No executions yet. Run a simulated test before activation.",
  "out.improvements": "Improvements",
  "out.duplicate": "Duplicate",
  "out.test": "Test",
  "out.pause": "Pause",
  "out.activate": "Activate",
  "out.actionFailed": "Action failed",

  // ——— Composer ———
  "comp.eyebrow": "AI AGENT BUILDER",
  "comp.title": "Build an agent",
  "comp.draft": "Draft saved locally",
  "comp.save": "Save agent",
  "comp.architect": "Build assistant",
  "comp.architectSub": "Compiles only approved operations",
  "comp.online": "ONLINE",
  "comp.you": "You",
  "comp.greeting": "Describe the result you want. I’ll identify the trigger, the actions and the required connections, and only ask what a safe plan cannot go without.",
  "comp.requiredDetail": "REQUIRED DETAIL",
  "comp.answerPlaceholder": "Where the result should go…",
  "comp.buildPlan": "Build the executable plan",
  "comp.validating": "Validating intent, security and cost…",
  "comp.tryExample": "TRY AN EXAMPLE",
  "comp.modifyPlaceholder": "Add an approval, change a tool, make it cheaper…",
  "comp.describePlaceholder": "Describe what the agent should do…",
  "comp.hint": "Try: “Retry failures three times”",
  "comp.send": "Send message",
  "comp.tabPlan": "Plan",
  "comp.tabTechnical": "Flow",
  "comp.tabTest": "Test data",
  "comp.tabSettings": "Settings",
  "comp.tabVersions": "Versions",
  "comp.emptyTitle": "Your plan will appear here",
  "comp.emptyCopy": "Rezaru will turn your objective into a readable plan, a list of required connections and a validated technical flow.",
  "comp.pendingTitle": "Technical flow pending",
  "comp.pendingCopy": "Answer the required questions and Rezaru will build an executable graph.",
  "comp.sampleTitle": "Sample trigger data",
  "comp.sampleCopy": "This data is isolated from production and marked as a simulated test.",
  "comp.validateSample": "Validate sample data",
  "comp.execSettings": "Execution settings",
  "comp.concurrency": "Concurrency",
  "comp.concurrencyUnit": "executions",
  "comp.timeout": "Default timeout",
  "comp.timezone": "Timezone",
  "comp.retention": "Retention",
  "comp.days": "days",
  "comp.currentDraft": "Current draft",
  "comp.createdBy": "Created by the Rezaru compiler",
  "comp.draftBadge": "Draft",
  "comp.versionNote": "After activation this version becomes immutable. Future edits create a new draft.",
  "comp.perMonth": "runs / month",
  "comp.saveReview": "Save and review",
  "comp.outcome": "OUTCOME",
  "comp.validated": "Validated",
  "comp.needsInput": "Needs input",
  "comp.connNeeded": "connections required",
  "comp.connNeededSub": "Connect them during review. Secrets never enter this plan.",
  "comp.assumptions": "ASSUMPTIONS",
  "comp.compileFailed": "The agent could not be compiled",
  "comp.saveFailed": "Could not save the agent",
  "comp.needDetailOne": "I understand the objective. I need one more detail before I can create a safe executable version.",
  "comp.needDetailMany": "I understand the objective. I need a few more details before I can create a safe executable version.",
  "comp.planReady": "The plan is ready.",
  "comp.planSteps": "steps",
  "comp.planConn": "required connections",
  "comp.planRuns": "monthly executions (estimated)",
  "comp.starter1": "Answer price and stock questions on Instagram.",
  "comp.starter2": "Every Monday send a summary of the week’s sales.",
  "comp.starter3": "Log Telegram orders into a spreadsheet.",
  "comp.starter4": "Remind the customer about their booking a day before.",

  // ——— Executions ———
  "exec.eyebrow": "RELIABLE EXECUTION",
  "exec.title": "Execution history",
  "exec.lead": "Inspect every run: steps, retries, waits, cost and output.",
  "exec.search": "Search executions…",
  "exec.filterStatus": "Filter by status",
  "exec.fSucceeded": "Succeeded",
  "exec.fFailed": "Failed",
  "exec.fRunning": "Running",
  "exec.filters": "Filters",
  "exec.colOutcome": "Agent",
  "exec.colStatus": "Status",
  "exec.colStarted": "Started",
  "exec.colDuration": "Duration",
  "exec.colSteps": "Steps",
  "exec.simulated": "Simulated execution",
  "exec.emptyTitle": "No executions yet",
  "exec.emptyCopy": "Test an agent with simulated data or activate it to begin collecting history.",
  "exec.back": "Execution history",
  "exec.workflowVersion": "Flow v",
  "exec.execution": "Execution",
  "exec.duration": "Duration",
  "exec.inProgress": "In progress",
  "exec.cost": "Estimated cost",
  "exec.tokens": "AI tokens",
  "exec.started": "Started",
  "exec.triggerInput": "Trigger input",
  "exec.triggerInputSub": "Secrets and configured redact fields are masked before display.",
  "exec.metadata": "Execution metadata",
  "exec.metaOutcome": "Agent",
  "exec.metaVersion": "Version",
  "exec.metaMode": "Mode",
  "exec.metaSteps": "Steps",
  "exec.live": "Live updates connected",
  "exec.timeline": "Execution timeline",
  "exec.cancel": "Cancel",
  "exec.retry": "Retry failed step",
  "exec.step": "STEP",
  "exec.attempt": "attempt",
  "exec.attempts": "attempts",
  "exec.ms": "ms",
  "exec.input": "Input",
  "exec.output": "Output",
  "exec.error": "Error",
  "exec.logs": "Structured logs",
  "exec.debugTitle": "AI debugging",
  "exec.debugSub": "Uses only this execution’s recorded evidence",
  "exec.whyFailed": "Why did this fail?",
  "exec.plainLanguage": "Explain without technical language",
  "exec.proposeFix": "Propose a fix",
  "exec.addFallback": "Add a fallback suggestion",
  "exec.reviewing": "Reviewing verified logs…",
  "exec.noExplanation": "No verified explanation is available.",

  // ——— Flow ———
  "flow.aria": "Read-only agent workflow graph",
  "flow.yes": "yes",
  "flow.no": "no",
  "flow.trigger": "trigger",
  "flow.action": "action",
  "flow.condition": "condition",
  "flow.transform": "transform",
  "flow.delay": "delay",
  "flow.approval": "approval",
  "flow.ai_task": "AI task",
  "flow.startNode": "Start",

  // ——— Connections ———
  "conn.eyebrow": "SECURE INTEGRATIONS",
  "conn.title": "Connections",
  "conn.lead": "Connect the tools Rezaru can use on your behalf. Secrets stay encrypted and server-side.",
  "conn.yours": "Your connections",
  "conn.configured": "configured",
  "conn.usedBy": "used by agents:",
  "conn.test": "Test",
  "conn.delete": "Delete",
  "conn.market": "Connector marketplace",
  "conn.approved": "approved connectors",
  "conn.search": "Search connectors…",
  "conn.all": "All",
  "conn.connected": "Connected",
  "conn.noCreds": "No credentials",
  "conn.addAnother": "Add another",
  "conn.connect": "Connect",
  "conn.dialogTitle": "Connect",
  "conn.oauthSetup": "OAuth setup",
  "conn.oauthCopy": "For hosted OAuth, configure:",
  "conn.oauthTail": "An existing access token can be used below for local development.",
  "conn.name": "Connection name",
  "conn.connectionString": "Connection string",
  "conn.apiKey": "API key",
  "conn.accessToken": "OAuth access token",
  "conn.credPlaceholderDev": "Use “demo” for a simulated connection",
  "conn.credPlaceholder": "Stored encrypted",
  "conn.connectAndTest": "Connect and test",
  "conn.failed": "Could not connect",
  "conn.testFailed": "Test failed",
  "conn.confirmDelete": "Delete this connection? Encrypted credentials will be removed with it.",
  "conn.suffix": " connection",
  "conn.docs": "Where to find these values — step-by-step guide",
  "conn.channels": "Channels",
  "conn.catCommunication": "Email and chat",
  "conn.catCRM": "CRM",
  "conn.catMarketing": "Marketing",
  "conn.catFinance": "Finance",
  "conn.catDatabases": "Databases",
  "conn.catAI": "AI",
  "conn.catDeveloper": "For developers",
  "conn.catProductivity": "Data",

  // ——— Templates ———
  "tpl.eyebrow": "AGENT MARKETPLACE",
  "tpl.title": "Templates",
  "tpl.lead": "Start from a proven scenario and configure only what is specific to you.",
  "tpl.search": "Search templates…",
  "tpl.all": "All",
  "tpl.setup": "min setup",
  "tpl.saves": "Saves",
  "tpl.savesUnit": "h/mo",
  "tpl.preview": "Preview template",
  "tpl.minutes": "minutes to configure",
  "tpl.savesAbout": "Saves about",
  "tpl.hoursMonth": "hours / month",
  "tpl.requiredConn": "Required connections",
  "tpl.install": "Install as draft",
  "tpl.installFailed": "Installation failed",

  // ——— Import ———
  "imp.eyebrow": "SAFE MIGRATION",
  "imp.title": "Import from n8n",
  "imp.lead": "Analyze compatibility, map credentials and test the converted agent before activation.",
  "imp.upload": "Upload JSON",
  "imp.orPaste": "or paste the export below",
  "imp.analyze": "Analyze compatibility",
  "imp.next": "What happens next",
  "imp.next1": "We detect every exported node",
  "imp.next2": "Supported nodes map to approved operations",
  "imp.next3": "Partial nodes are highlighted for review",
  "imp.next4": "Unsupported code becomes a safe placeholder",
  "imp.next5": "The original JSON is preserved",
  "imp.next6": "Nothing runs until you test and activate",
  "imp.report": "N8N COMPATIBILITY REPORT",
  "imp.nodesAnalyzed": "nodes analyzed",
  "imp.convertible": "convertible",
  "imp.supported": "Supported",
  "imp.partial": "Partial",
  "imp.manual": "Manual review",
  "imp.colNode": "Node",
  "imp.colType": "n8n type",
  "imp.colOperation": "Rezaru operation",
  "imp.colCompat": "Compatibility",
  "imp.placeholder": "Manual review placeholder",
  "imp.backToSource": "Back to source",
  "imp.convert": "Convert to draft agent",
  "imp.badJson": "The pasted content is not valid JSON.",
  "imp.tooBig": "The n8n export must be smaller than 5 MB.",
  "imp.analysisFailed": "Analysis failed",
  "imp.conversionFailed": "Conversion failed",

  // ——— Team ———
  "team.eyebrow": "PEOPLE & PERMISSIONS",
  "team.title": "Team",
  "team.lead": "Give everyone exactly the access they need.",
  "team.members": "Workspace members",
  "team.membersCount": "people have access.",
  "team.colMember": "Member",
  "team.colRole": "Role",
  "team.colAccess": "Access",
  "team.unnamed": "Unnamed member",
  "team.owner": "Owner",
  "team.accessRead": "Read-only",
  "team.accessRun": "Run & approve",
  "team.accessBuild": "Build & manage",
  "team.invite": "Invite a teammate",
  "team.inviteSub": "Invitation links expire after seven days.",
  "team.inviteEmail": "Email",
  "team.inviteEmailPlaceholder": "teammate@company.com",
  "team.inviteRole": "Role",
  "team.inviteCreate": "Create invitation",
  "team.inviteFailed": "Could not send the invitation",
  "team.inviteCreated": "Invitation created. Email delivery uses the configured mail service.",
  "team.copyInvite": "Copy invitation link",
  "team.pending": "Pending invitations",
  "team.expires": "Expires",
  "team.roleGuide": "What each role can do",
  "team.roleOwner": "Owner",
  "team.roleOwnerCopy": "Everything, including ownership and billing",
  "team.roleAdmin": "Admin",
  "team.roleAdminCopy": "Team, billing, connections and agents",
  "team.roleBuilder": "Builder",
  "team.roleBuilderCopy": "Create, edit, test and connect",
  "team.roleOperator": "Operator",
  "team.roleOperatorCopy": "Run, pause, retry and approve",
  "team.roleViewer": "Viewer",
  "team.roleViewerCopy": "Read agents and execution history",

  // ——— Usage ———
  "usage.eyebrow": "METERING & LIMITS",
  "usage.title": "Usage",
  "usage.lead": "Transparent workspace consumption for the current billing period.",
  "usage.managePlan": "Manage plan",
  "usage.currentPlan": "Current plan",
  "usage.period": "Billing period",
  "usage.periodValue": "This calendar month",
  "usage.behavior": "Limit behavior",
  "usage.behaviorValue": "Excess runs pause safely",
  "usage.custom": "Custom",
  "usage.used": "used",
  "usage.levelWarning": "Approaching plan allowance",
  "usage.levelCritical": "Upgrade recommended",
  "usage.levelBlocked": "Limit reached",
  "usage.levelOk": "Within allowance",
  "usage.mOutcomes": "Active agents",
  "usage.mExecutions": "Conversations",
  "usage.mCredits": "AI credits",
  "usage.mMembers": "Team members",
  "usage.noticeTitle": "Plan limits are enforced on the server",
  "usage.noticeCopy": "Rezaru never deletes agents when a limit is reached. Excess executions pause and surface an upgrade request.",

  // ——— Billing ———
  "bill.eyebrow": "PLAN & BILLING",
  "bill.title": "Billing",
  "bill.lead": "Choose the operating capacity your business needs.",
  "bill.devTitle": "Development billing mode",
  "bill.devCopy": "Stripe credentials are not configured. Plan changes update local limits and never create a charge.",
  "bill.current": "CURRENT PLAN",
  "bill.plan": "PLAN",
  "bill.localSub": "Local development subscription",
  "bill.stripeSub": "Managed securely through Stripe",
  "bill.manageSub": "Manage subscription",
  "bill.monthly": "Monthly",
  "bill.annual": "Annual",
  "bill.save20": "Save 20%",
  "bill.perMonth": "/month",
  "bill.currentPlan": "Current plan",
  "bill.choose": "Choose",
  "bill.nameFree": "Trial",
  "bill.namePro": "Start",
  "bill.nameTeam": "Business",
  "bill.nameBusiness": "Network",
  "bill.freeCopy": "14 days to try it on your own work",
  "bill.proCopy": "When customers write a few times a day",
  "bill.teamCopy": "When there are many messages every day",
  "bill.businessCopy": "Several locations or teams",
  "bill.proF1": "Up to 300 conversations a month",
  "bill.proF2": "One channel of your choice",
  "bill.proF3": "Knowledge base from your price list",
  "bill.proF4": "Calendar booking",
  "bill.proF5": "Email support",
  "bill.teamF1": "Up to 2,000 conversations a month",
  "bill.teamF2": "All channels at once",
  "bill.teamF3": "Reminders and upsells",
  "bill.teamF4": "Reports and summaries",
  "bill.teamF5": "Priority support",
  "bill.businessF1": "Several locations and teams",
  "bill.businessF2": "Your own tone of voice",
  "bill.businessF3": "Integrations built for you",
  "bill.businessF4": "A dedicated manager",
  "bill.businessTitle": "Several locations, custom integrations and an SLA.",
  "bill.businessPrice": "Custom",
  "bill.businessNote": "Depends on the number of locations and conversation volume",
  "bill.contact": "Talk to us",
  "bill.trialNote": "First 14 days free. No card needed, nothing is charged automatically.",
  "bill.failed": "Billing action failed",
  "bill.updated": "Plan updated",
  "bill.portalUnavailable": "Customer portal unavailable",

  // ——— Settings ———
  "set.eyebrow": "WORKSPACE CONFIGURATION",
  "set.title": "Settings",
  "set.lead": "Workspace identity and default operational preferences.",
  "set.general": "General",
  "set.security": "Security & audit",
  "set.apiKeys": "API keys",
  "set.webhooks": "Webhooks",
  "set.details": "Workspace details",
  "set.detailsSub": "Used in navigation, invitations and billing records.",
  "set.name": "Workspace name",
  "set.slug": "Workspace slug",
  "set.dept": "Department",
  "set.size": "Company size",
  "set.saveSettings": "Save settings",
  "set.groupSpace": "Workspace",
  "set.groupDev": "For developers",
  "set.back": "Back to settings",

  // ——— Security ———
  "sec.eyebrow": "SECURITY & TRUST",
  "sec.title": "Security",
  "sec.lead": "Credential protection, authorization controls and workspace audit evidence.",
  "sec.encTitle": "Encrypted credentials",
  "sec.encCopy": "AES-256-GCM authenticated encryption with separate secret records.",
  "sec.isoTitle": "Workspace isolation",
  "sec.isoCopy": "Every resource query is scoped to the authenticated workspace.",
  "sec.keyTitle": "Hashed API keys",
  "sec.keyCopy": "Full developer keys are shown once and never stored in recoverable form.",
  "sec.audit": "Audit log",
  "sec.auditSub": "Security-sensitive workspace activity.",
  "sec.system": "System",

  // ——— API keys ———
  "key.eyebrow": "DEVELOPER ACCESS",
  "key.title": "API keys",
  "key.lead": "Trigger agents and inspect executions from your own product.",
  "key.copyNow": "Copy this key now",
  "key.copyNowSub": "It will not be shown again.",
  "key.list": "Workspace API keys",
  "key.listSub": "Only prefixes and hashes are stored.",
  "key.used": "Used",
  "key.neverUsed": "Never used",
  "key.none": "No API keys have been created.",
  "key.create": "Create API key",
  "key.createSub": "Use the least privilege needed by the integration.",
  "key.name": "Key name",
  "key.namePlaceholder": "Production backend",
  "key.scopes": "Scopes",
  "key.generate": "Generate key",
  "key.confirmRevoke": "Revoke this API key? Existing integrations using it will stop working.",
  "key.quickstart": "Developer API quickstart",
  "key.quickstartSub": "Use a bearer token and JSON requests. Rate limits apply per key.",
  "key.epList": "List agents",
  "key.epTrigger": "Trigger an agent",
  "key.epExecutions": "List executions",
  "key.epExecution": "Execution details",

  // ——— Webhooks ———
  "hook.eyebrow": "INBOUND EVENTS",
  "hook.title": "Webhooks",
  "hook.lead": "Create test and production endpoints with optional secret verification.",
  "hook.copyNow": "Copy this webhook URL now",
  "hook.copyNowSub": "The full token will not be shown again.",
  "hook.list": "Webhook endpoints",
  "hook.listSub": "Test endpoints simulate executions; production endpoints require an active agent.",
  "hook.created": "Created",
  "hook.sample": "Sample captured",
  "hook.none": "No webhook endpoints yet.",
  "hook.create": "Create endpoint",
  "hook.createSub": "The unguessable URL is shown once. Optionally require an additional secret header.",
  "hook.outcome": "Agent",
  "hook.mode": "Mode",
  "hook.modeTest": "Test — simulated",
  "hook.modeProd": "Production — real execution",
  "hook.secret": "Verification secret (optional)",
  "hook.secretPlaceholder": "Sent as x-rezaru-secret",
  "hook.createSecure": "Create secure endpoint"
};

export const uiCopy: Record<Lang, Record<UiCopyKey, string>> = { ru, en };

/**
 * Status labels come from the database as enum names, so they cannot be typed
 * keys. Anything unmapped falls back to the readable form of the raw value.
 */
export function statusLabel(lang: Lang, status: string): string {
  return lookup(lang, `status.${status}`) ?? status.replaceAll("_", " ").toLowerCase();
}

/** Same for workspace roles, which also arrive as enum names. */
export function roleLabel(lang: Lang, role: string): string {
  return lookup(lang, `role.${role}`) ?? role.toLowerCase();
}

function lookup(lang: Lang, key: string): string | undefined {
  return (uiCopy[lang] as Record<string, string | undefined>)[key];
}
